---
- name: My first web project by Ansible
  become: yes
  hosts: WEB

  tasks:
  - name: Installing web server on RedHat
    yum:
      name: httpd
      state: latest

  - name: Copy index file on web server
    copy:
      src: index.html
      dest: /var/www/html/
      mode: 0444
    notify: Restart Web Server

  - name: Starting Apache and enable it on the boot
    service:
      name: httpd
      state: started
      enabled: yes

  handlers:
  - name: Restart Web Server
    service:
      name: httpd
      state: restarted
